### ISSUE TITLE
Support empty cells in create_valid_ddf_id.m 

### ISSUE THREAD

**Issue by olarosling** [open-numbers/m-scripts#37]
Empty cells should just continue to be empty Currently we get this error, See bottom of this comment.
In my new Example xlsx file here row 12 is empty to ensure we don't put Error 
https://github.com/open-numbers/m-scripts/blob/master/examples/identifiers/example%20create_valid_ddf_ids.xlsx

Expression.Error: We cannot convert the value null to type Text.
Details:
Value=
Type=Type

**Comment by srasel** [comment]
@olarosling: this issue should be fixed with the pull request

**Comment by olarosling** [comment]
I tested it, and it works fine! Thanks @srasel !
